### PR TITLE
fix bugs: crashes, packages info not correctly displayed

### PR DESCRIPTION
**Pull request by ArchieMeng**
## fix bugs:
- crashes in AddActivity when network needs log in.
- crashes on some platform when set process bar color.
- BaiShi express' packages info are not displayed correctly
- crash when package name was set empty.
## add function:
- Enable SplashActivity when launch app from launcher, making this app looks even more smoooooth.

### CODE REVIEW

**Comment by ArchieMeng** [comment]
please test it.

**Comment by coderfox** [comment]
I think this PR does not actually fix #26 as the location hint is still broken.
I suggest a better way is to create different adapters for various express companies and provide a default one with a switch.

**Comment by coderfox** [comment]
But what you are doing can be a possible update to the default adapter as it does not corrupts the message.

**Comment by ArchieMeng** [comment]
I still don't get you point, what is the correct output

**Comment by coderfox** [comment]
There is a location hint next to the time of each status, but for BaiShi Express it's broken.
You may use a result from other companies to check the correct behavior.

**Comment by ArchieMeng** [comment]
I got it.I will work for it later.

**Comment by ArchieMeng** [comment]
@coderfox fix location hints,please have a try.
If location hints is still display incorrectly, remove it and add it again

**Comment by coderfox** [comment]
I found a bug in the PR.
When using an inexist package number, e.g. `426506386588`, the package cannot be forced to add.

**Comment by coderfox** [comment]
And I don't think your modification is a good approach to the fix as the status beautify is broken.
For example, in the original version the source status may be `【广州市】投递并签收，签收人：他人收 李生` and then beautified to `投递并签收，签收人：他人收 李生` with location hint `广州市`, and in your version it is not beautified.

**Comment by ArchieMeng** [comment]
@coderfox Yes, I got it.
According to your first reply, this is an ugly fix of the case when PackageTracker can not get correct return page (a login page, or some other things).In the master version, this will cause a crash, so I just fix it by an ugly way.
And to your second reply, I feel sorry.Because I have asked the author, and he told me it is unnecessary to beautify the original information due to complex forms of JSON data referring to different express company. If we can not find a way to beautify JSON data of every express company, it may case loss of information to express like BaiShi Express (百世汇通). So I removed it.

**Comment by coderfox** [comment]
For the first issue, I see why the results are such, but I think it may be better to perform a toast to inform the user.
For the second one, I suggest to specially adapt beautifier and hinter for each company, and for supported ones, do beautify while for unsupported ones don't.

**Comment by ArchieMeng** [comment]
Ok, I will fix it, but I can't write beautify adapter.

**Comment by coderfox** [comment]
Well, I'm preparing an exam, so I cannot do it currently, but I can work on it after 4 months.
Thanks for your help :)

**Pull request merged**
