### PR TITLE
Project: Entire Company List

### PR DESCRIPTION
**Pull request by coderfox**
This PR fixes the company list of Kuaidi100 API.

In fact, there happens to be <http://www.kuaidi100.com/js/share/company.js> giving out the entire list of companies, but I don't know how to parse it, so I just hard-coded it.
If you have better solutions, you may just close this PR.

And I wrote an automatic tool to build up the list, you may attach these code after the `company.js` downloaded and run `node company.js`
```js
for(let com of jsoncom.company){
  console.log(`info.add(new Company("${com.companyname}", "${com.code}", "${com.tel}", "${com.comurl}"));`)
}
```

### CODE REVIEW

**Comment by fython** [comment]
Thank you very much. BTW, I want to remove something not frequently used. (I can do this by myself)

**Comment by fython** [comment]
> In fact, there happens to be http://www.kuaidi100.com/js/share/company.js giving out the entire list of companies, but I don't know how to parse it, so I just hard-coded it.

Maybe I will make app to pull it dynamically.

**Comment by lmy441900** [comment]
> In fact, there happens to be http://www.kuaidi100.com/js/share/company.js giving out the entire list of companies, but I don't know how to parse it, so I just hard-coded it.

This is a JSON object. Use some libraries to parse it. (I remember that Java has such class library)

**Comment by coderfox** [comment]
It is not JSON, it is JavaScript, though it may be easily converted to JSON.

Junde Yhi <notifications@github.com>于2016年7月11日周一 22:39写道：

**Comment by fython** [comment]
@coderfox Delete the string "var jsoncom=" and replace all the apostrophes with double quotes. Then it will be converted to JSON format.

**Comment by lmy441900** [comment]
> @coderfox Delete the string "var jsoncom=" and replace all the apostrophes with double quotes. Then it will be converted to JSON format.

So is it easy to embed a module that interpret JavaScript? If not, we can try this.

**Pull request merged**
